package ec.edu.ucuenca.test01;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Cliente")
public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Age")
   private java.lang.Integer age;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("Sex")
   private java.lang.String sex;

   public Customer()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSex()
   {
      return this.sex;
   }

   public void setSex(java.lang.String sex)
   {
      this.sex = sex;
   }

   public Customer(java.lang.Integer age, java.lang.String name,
         java.lang.String sex)
   {
      this.age = age;
      this.name = name;
      this.sex = sex;
   }

}