package ec.edu.ucuenca.prueba3;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SolicitudPrueba3 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SOLICITUDPRUEBA3_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "SOLICITUDPRUEBA3_ID_SEQ", name = "SOLICITUDPRUEBA3_ID_GENERATOR")
    private java.lang.Long id;

    public SolicitudPrueba3() {
    }
    
    public SolicitudPrueba3(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}