package ec.edu.ucuenca.aprobacion;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Student implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STUDENT_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "STUDENT_ID_SEQ", name = "STUDENT_ID_GENERATOR")
    private java.lang.Long id;

    public Student() {
    }
    
    public Student(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}