package ec.edu.ucuenca.aprobacion;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity(name = "student")
@org.kie.api.definition.type.TypeSafe(true)
@javax.persistence.Table(name = "Student")
public class Student implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.Column(name = "elegible")
   private java.lang.Boolean elegible;

   @javax.persistence.Column(name = "gpa")
   private java.lang.Float gpa;

   @javax.persistence.Column(name = "name")
   private java.lang.String name;

   public Student()
   {
   }

   public java.lang.Boolean getElegible()
   {
      return this.elegible;
   }

   public void setElegible(java.lang.Boolean elegible)
   {
      this.elegible = elegible;
   }

   public java.lang.Float getGpa()
   {
      return this.gpa;
   }

   public void setGpa(java.lang.Float gpa)
   {
      this.gpa = gpa;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Student(java.lang.Boolean elegible, java.lang.Float gpa,
         java.lang.String name)
   {
      this.elegible = elegible;
      this.gpa = gpa;
      this.name = name;
   }

}