package ec.edu.ucuenca.prueba1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Solicitud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SOLICITUD_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "SOLICITUD_ID_SEQ", name = "SOLICITUD_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "nombre")
   private java.lang.String nombre;

   @org.kie.api.definition.type.Label(value = "descripcion")
   private java.lang.String descripcion;

   @org.kie.api.definition.type.Label(value = "aprobar")
   private java.lang.String aprobar;

   public Solicitud()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(java.lang.String descripcion)
   {
      this.descripcion = descripcion;
   }

   public java.lang.String getAprobar()
   {
      return this.aprobar;
   }

   public void setAprobar(java.lang.String aprobar)
   {
      this.aprobar = aprobar;
   }

   public Solicitud(java.lang.Long id, java.lang.String nombre,
         java.lang.String descripcion, java.lang.String aprobar)
   {
      this.id = id;
      this.nombre = nombre;
      this.descripcion = descripcion;
      this.aprobar = aprobar;
   }

}