package ec.edu.ucuenca.reasignaciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity(name = "Reasignacion")
@javax.persistence.Table(schema = "public", name = "Reasignacion")
public class Reasignacion 
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REASIGNACION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "REASIGNACION_ID_SEQ", name = "REASIGNACION_ID_GENERATOR")
   private java.lang.Long id;

   private java.util.Date fecha;

   private java.lang.String accionRealizada;

   private java.lang.String acccionARealizar;

   private java.lang.String usuarioDestino;

   private java.lang.String usuarioOrigen;

   public Reasignacion()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public java.lang.String getAccionRealizada()
   {
      return this.accionRealizada;
   }

   public void setAccionRealizada(java.lang.String accionRealizada)
   {
      this.accionRealizada = accionRealizada;
   }

   public java.lang.String getAcccionARealizar()
   {
      return this.acccionARealizar;
   }

   public void setAcccionARealizar(java.lang.String acccionARealizar)
   {
      this.acccionARealizar = acccionARealizar;
   }

   public java.lang.String getUsuarioDestino()
   {
      return this.usuarioDestino;
   }

   public void setUsuarioDestino(java.lang.String usuarioDestino)
   {
      this.usuarioDestino = usuarioDestino;
   }

   public java.lang.String getUsuarioOrigen()
   {
      return this.usuarioOrigen;
   }

   public void setUsuarioOrigen(java.lang.String usuarioOrigen)
   {
      this.usuarioOrigen = usuarioOrigen;
   }

   public Reasignacion(java.lang.Long id, java.util.Date fecha,
         java.lang.String accionRealizada, java.lang.String acccionARealizar,
         java.lang.String usuarioDestino, java.lang.String usuarioOrigen)
   {
      this.id = id;
      this.fecha = fecha;
      this.accionRealizada = accionRealizada;
      this.acccionARealizar = acccionARealizar;
      this.usuarioDestino = usuarioDestino;
      this.usuarioOrigen = usuarioOrigen;
   }

}