package ec.edu.ucuenca.registrotramites;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Tramite implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRAMITE_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "TRAMITE_ID_SEQ", name = "TRAMITE_ID_GENERATOR")
    private java.lang.Long id;

    public Tramite() {
    }
    
    public Tramite(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}